version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sweetalert2
    versions:
    - 10.14.0
    - 10.14.1
    - 10.15.0
    - 10.15.1
    - 10.15.2
    - 10.15.4
    - 10.15.5
    - 10.15.6
    - 10.15.7
    - 10.16.0
    - 10.16.2
    - 10.16.4
    - 10.16.5
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-toastify
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: redux
    versions:
    - 4.0.5
